### ISSUE TITLE
Document use cases for adding Publish vs Unpublished data functionality

### ISSUE THREAD

**Issue by daremiyo** [RockefellerArchiveCenter/rac_aspace#29]
**Is your feature request related to a problem? Please describe.**
May be useful to describe functionality in the Data Helpers section of the README that targets Publish vs. Unpublished data on archival objects and their associated child objects. Can retrieve data on top level to determine what resources are published or unpublished and can also retrieve data on unpublished child objects that may be buried in larger resource records.

**Describe the solution you'd like**
Add bullet point to Retrieve and Modify subsection of Data Helpers to refer to Publish vs. Unpublished data.

**Describe alternatives you've considered**
May better fit under Infer and Modify or other subsections of Data Helpers.

**Comment by helrond** [comment]
Can we get a few use-case examples here (or links to other code that does this kind of thing)? I'm not sure I see the benefit in a function to check if an object is published, since that's really about checking the `publish` property on that object. BUT, if there are things like "I want a list of all the unpublished archival objects associated with this resource" that's a different thing!

**Comment by helrond** [comment]
Closing after discussion because we can't come up with any use cases.
